### PR TITLE
Update LaTeX file

### PR DESCRIPTION
**Pull request by Jason-vh**
Additions:

- The new Data diagrams
- Description, Requirements, Constrains etc for the Surveillance module

Changes:

- The Data activity and use-case diagrams
- The Surveillance diagrams
- The User class diagram

Deletions:

- Removed description of n-tier.

I removed my description of n-tier as I realized that I was quite mistaken. We need someone who knows what they're doing (Dieumerci maybe) to write that.
I'm assigning @PeterRayner   and @SirJosh  as I changed your stuff - please make sure that what I changed was correct.
[Here](https://github.com/PeterRayner/COS301_Team_Haskell_Phase2/files/822098/ArchitecturalRequirements.1.pdf) is the compiled PDF.

### CODE REVIEW

**Review by SirJosh — CHANGES_REQUESTED** [review]
Please update the data activity diagram as the arrows are pointing incorrectly. Can you also update my student number to 14152152

**Comment by BernhardSchuld** [comment]
My student number is also wrong. On the current master branch's tex file it is correct though (my correct student number is 10297902)

EDIT: Seems it has been fixed

**Comment by Jason-vh** [comment]
> My student number is also wrong. On the current master branch's tex file it is correct though (my correct student number is 10297902)
EDIT: Seems it has been fixed

Apologies, not sure how that happened.
I also have no idea who fixed it - it wasn't me.

**Comment by Jason-vh** [comment]
Ok I've merged all the fixes as requested.

- Bernhard's student number is fixed.
- @SirJosh's student number is fixed.
- The Data activity diagrams are fixed.
- Fixed merge conflicts.

[Here](https://github.com/PeterRayner/COS301_Team_Haskell_Phase2/files/824210/ArchitecturalRequirements.3.pdf) is the newly compiled pdf.

**Review by SirJosh — APPROVED** [review]

**Pull request closed without merging**
